language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION='2.7.*'
    - php: 7.0
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.1.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.2.*'

before_install:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update --prefer-dist --no-interaction

script:
  - if [ "$SYMFONY_VERSION" == "3.2.*" ]; then ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; else ./vendor/bin/phpunit --coverage-text; fi

after_script:
  - if [ "$SYMFONY_VERSION" == "3.2.*" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$SYMFONY_VERSION" == "3.2.*" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
